databases:
  - name: project_conversation
    databaseName: project_conversation
    user: project_conversation
    plan: free

services:
  - type: web
    plan: free
    name: project_conversation
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project_conversation
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
